# vim: ft=yaml.docker-compose
name: uptime-kuma

include:
  - ext/docker-compose-snippets/tailscale-caddy.yaml
  - ext/docker-compose-snippets/simple-reverse-proxy.yaml
  - ext/docker-compose-snippets/volume-backup-schedules.yaml

services:
  uptime-kuma:
    image: ghcr.io/rahulsalvi/uptime-kuma:latest
    environment:
      HOST: 127.0.0.1
      PORT: 8080
      NODE_OPTIONS: --use-openssl-ca
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped
    extends:
      file: ext/docker-compose-snippets/tailscale-app-base.yaml
      service: tailscale-app-base

  backup:
    volumes:
      - uptime-kuma-data:/backup:ro
    extends:
      file: ext/docker-compose-snippets/volume-backup.yaml
      service: aws-backup-infrequent

volumes:
  uptime-kuma-data:
